import { Item, Sale } from '@/types';

// Helper to generate IDs
const id = (prefix: string, n: number) => `${prefix}-mock-${n}`;

// Dates relative to today
function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().split('T')[0];
}

export const MOCK_ITEMS: Item[] = [
  {
    id: id('item', 1),
    name: 'iPhone 12 64GB',
    description: 'Tela sem trincas, bateria 87%, caixa original',
    category: 'Eletrônicos',
    photoUrl: '',
    purchaseDate: daysAgo(45),
    purchasePrice: 850,
    condition: 'used',
    supplier: 'Marketplace',
    status: 'sold',
    suggestedPrice: 1275,
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
  {
    id: id('item', 2),
    name: 'Nike Air Max 90',
    description: 'Tênis tamanho 42, usado poucas vezes',
    category: 'Calçados',
    photoUrl: '',
    purchaseDate: daysAgo(30),
    purchasePrice: 120,
    condition: 'like-new',
    supplier: 'Brechó Online',
    status: 'sold',
    suggestedPrice: 220,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: id('item', 3),
    name: 'MacBook Air M1',
    description: 'MacBook Air 2020, 8GB RAM, 256GB SSD',
    category: 'Eletrônicos',
    photoUrl: '',
    purchaseDate: daysAgo(20),
    purchasePrice: 3200,
    condition: 'like-new',
    supplier: 'Amigo',
    status: 'available',
    suggestedPrice: 4800,
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: id('item', 4),
    name: 'Jaqueta Zara M',
    description: 'Jaqueta couro sintético, tamanho M, preta',
    category: 'Roupas',
    photoUrl: '',
    purchaseDate: daysAgo(15),
    purchasePrice: 60,
    condition: 'used',
    supplier: 'Bazar',
    status: 'available',
    suggestedPrice: 110,
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: id('item', 5),
    name: 'Cadeira Gamer RGB',
    description: 'Cadeira gamer preta e vermelha, reclinável',
    category: 'Móveis',
    photoUrl: '',
    purchaseDate: daysAgo(10),
    purchasePrice: 350,
    condition: 'used',
    supplier: 'Facebook Marketplace',
    status: 'reserved',
    suggestedPrice: 580,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: id('item', 6),
    name: 'AirPods Pro 2ª Geração',
    description: 'Com estojo de carga, cabo lightning incluso',
    category: 'Eletrônicos',
    photoUrl: '',
    purchaseDate: daysAgo(8),
    purchasePrice: 680,
    condition: 'like-new',
    supplier: 'OLX',
    status: 'available',
    suggestedPrice: 1050,
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: id('item', 7),
    name: 'Relógio Casio G-Shock',
    description: 'G-Shock original, pulseira borracha preta',
    category: 'Acessórios',
    photoUrl: '',
    purchaseDate: daysAgo(5),
    purchasePrice: 180,
    condition: 'used',
    supplier: 'Shopee',
    status: 'available',
    suggestedPrice: 290,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: id('item', 8),
    name: 'Kindle Paperwhite',
    description: '11ª geração, 8GB, sem luz, capa incluída',
    category: 'Eletrônicos',
    photoUrl: '',
    purchaseDate: daysAgo(3),
    purchasePrice: 280,
    condition: 'like-new',
    supplier: 'Amigo',
    status: 'available',
    suggestedPrice: 430,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
];

// Build sales for sold items referencing historical data
function makeSale(
  item: Item,
  salePrice: number,
  daysAfterPurchase: number,
  buyer: string,
  method: Sale['paymentMethod'],
): Sale {
  const saleDate = new Date(item.purchaseDate);
  saleDate.setDate(saleDate.getDate() + daysAfterPurchase);
  const profit = salePrice - item.purchasePrice;
  const margin = (profit / item.purchasePrice) * 100;
  return {
    id: `sale-mock-${item.id}`,
    itemId: item.id,
    itemName: item.name,
    itemCategory: item.category,
    salePrice,
    purchasePrice: item.purchasePrice,
    deliveryMethod: 'pickup',
    deliveryCost: 0,
    profit,
    marginPercent: margin,
    paymentMethod: method,
    buyer,
    saleDate: saleDate.toISOString().split('T')[0],
    createdAt: saleDate.toISOString(),
    photoUrl: item.photoUrl,
  };
}

const soldItem1 = MOCK_ITEMS[0]; // iPhone 12
const soldItem2 = MOCK_ITEMS[1]; // Nike

export const MOCK_SALES: Sale[] = [
  makeSale(soldItem1, 1350, 12, 'Carlos Silva', 'pix'),
  makeSale(soldItem2, 230, 8, 'Ana Oliveira', 'cash'),
  // Older sales (2–5 months ago) for historical chart
  {
    id: 'sale-mock-hist-1',
    itemId: 'hist-1',
    itemName: 'Samsung Galaxy A54',
    itemCategory: 'Eletrônicos',
    salePrice: 920,
    purchasePrice: 600,
    profit: 320,
    marginPercent: 53.33,
    paymentMethod: 'pix',
    buyer: 'João',
    saleDate: (() => { const d = new Date(); d.setMonth(d.getMonth() - 1); d.setDate(5); return d.toISOString().split('T')[0]; })(),
    createdAt: new Date().toISOString(),
    photoUrl: '',
    deliveryMethod: 'pickup',
    deliveryCost: 0,
  },
  {
    id: 'sale-mock-hist-2',
    itemId: 'hist-2',
    itemName: 'Calça Jeans Levis',
    itemCategory: 'Roupas',
    salePrice: 150,
    purchasePrice: 70,
    profit: 80,
    marginPercent: 114.28,
    paymentMethod: 'cash',
    buyer: 'Maria',
    saleDate: (() => { const d = new Date(); d.setMonth(d.getMonth() - 1); d.setDate(15); return d.toISOString().split('T')[0]; })(),
    createdAt: new Date().toISOString(),
    photoUrl: '',
    deliveryMethod: 'pickup',
    deliveryCost: 0,
  },
  {
    id: 'sale-mock-hist-3',
    itemId: 'hist-3',
    itemName: 'PS4 Slim 1TB',
    itemCategory: 'Eletrônicos',
    salePrice: 1100,
    purchasePrice: 750,
    profit: 350,
    marginPercent: 46.66,
    paymentMethod: 'card',
    buyer: 'Pedro',
    saleDate: (() => { const d = new Date(); d.setMonth(d.getMonth() - 2); d.setDate(10); return d.toISOString().split('T')[0]; })(),
    createdAt: new Date().toISOString(),
    photoUrl: '',
    deliveryMethod: 'pickup',
    deliveryCost: 0,
  },
  {
    id: 'sale-mock-hist-4',
    itemId: 'hist-4',
    itemName: 'Mesa de Escritório',
    itemCategory: 'Móveis',
    salePrice: 480,
    purchasePrice: 200,
    profit: 280,
    marginPercent: 140,
    paymentMethod: 'transfer',
    buyer: 'Lucia',
    saleDate: (() => { const d = new Date(); d.setMonth(d.getMonth() - 2); d.setDate(22); return d.toISOString().split('T')[0]; })(),
    createdAt: new Date().toISOString(),
    photoUrl: '',
    deliveryMethod: 'pickup',
    deliveryCost: 0,
  },
  {
    id: 'sale-mock-hist-5',
    itemId: 'hist-5',
    itemName: 'Fone JBL Tune 510BT',
    itemCategory: 'Eletrônicos',
    salePrice: 210,
    purchasePrice: 120,
    profit: 90,
    marginPercent: 75,
    paymentMethod: 'pix',
    buyer: 'Roberto',
    saleDate: (() => { const d = new Date(); d.setMonth(d.getMonth() - 3); d.setDate(8); return d.toISOString().split('T')[0]; })(),
    createdAt: new Date().toISOString(),
    photoUrl: '',
    deliveryMethod: 'pickup',
    deliveryCost: 0,
  },
  {
    id: 'sale-mock-hist-6',
    itemId: 'hist-6',
    itemName: 'Micro-ondas Electrolux 20L',
    itemCategory: 'Eletrodomésticos',
    salePrice: 320,
    purchasePrice: 150,
    profit: 170,
    marginPercent: 113.33,
    paymentMethod: 'pix',
    buyer: 'Fernanda',
    saleDate: (() => { const d = new Date(); d.setMonth(d.getMonth() - 3); d.setDate(18); return d.toISOString().split('T')[0]; })(),
    createdAt: new Date().toISOString(),
    photoUrl: '',
    deliveryMethod: 'pickup',
    deliveryCost: 0,
  },
  {
    id: 'sale-mock-hist-7',
    itemId: 'hist-7',
    itemName: 'Tênis Adidas Ultraboost',
    itemCategory: 'Calçados',
    salePrice: 380,
    purchasePrice: 200,
    profit: 180,
    marginPercent: 90,
    paymentMethod: 'card',
    buyer: 'Bruno',
    saleDate: (() => { const d = new Date(); d.setMonth(d.getMonth() - 4); d.setDate(3); return d.toISOString().split('T')[0]; })(),
    createdAt: new Date().toISOString(),
    photoUrl: '',
    deliveryMethod: 'pickup',
    deliveryCost: 0,
  },
  {
    id: 'sale-mock-hist-8',
    itemId: 'hist-8',
    itemName: 'Câmera Canon T6i',
    itemCategory: 'Eletrônicos',
    salePrice: 1800,
    purchasePrice: 1100,
    profit: 700,
    marginPercent: 63.6,
    paymentMethod: 'transfer',
    buyer: 'Amanda',
    saleDate: (() => { const d = new Date(); d.setMonth(d.getMonth() - 4); d.setDate(20); return d.toISOString().split('T')[0]; })(),
    createdAt: new Date().toISOString(),
    photoUrl: '',
    deliveryMethod: 'pickup',
    deliveryCost: 0,
  },
  {
    id: 'sale-mock-hist-9',
    itemId: 'hist-9',
    itemName: 'iPad 9ª Geração 64GB',
    itemCategory: 'Eletrônicos',
    salePrice: 1450,
    purchasePrice: 900,
    profit: 550,
    marginPercent: 61.1,
    paymentMethod: 'pix',
    buyer: 'Tiago',
    saleDate: (() => { const d = new Date(); d.setMonth(d.getMonth() - 5); d.setDate(12); return d.toISOString().split('T')[0]; })(),
    createdAt: new Date().toISOString(),
    photoUrl: '',
    deliveryMethod: 'pickup',
    deliveryCost: 0,
  },
  {
    id: 'sale-mock-hist-10',
    itemId: 'hist-10',
    itemName: 'Sofá 3 lugares',
    itemCategory: 'Móveis',
    salePrice: 850,
    purchasePrice: 400,
    profit: 450,
    marginPercent: 112.5,
    paymentMethod: 'transfer',
    buyer: 'Claudia',
    saleDate: (() => { const d = new Date(); d.setMonth(d.getMonth() - 5); d.setDate(25); return d.toISOString().split('T')[0]; })(),
    createdAt: new Date().toISOString(),
    photoUrl: '',
    deliveryMethod: 'pickup',
    deliveryCost: 0,
  },
];
